[[plugins]]
repo = "Raku/vim-raku"

[[plugins]]
repo = "ziglang/zig.vim"

[[plugins]]
repo = "rust-lang/rust.vim"

# HTML
[[plugins]]
repo = "mattn/emmet-vim"

# Clojure
[[plugins]]
repo = "liquidz/elin"
