[[plugins]]
repo = "luochen1990/rainbow"
hook_source = """
  let g:rainbow_active = 1
"""

[[plugins]]
repo = "itchyny/lightline.vim"
hook_source = """
  set laststatus=2
  set noshowmode
"""

[[plugins]]
repo = "vim-skk/skkeleton"
hook_source = """
  let s:jisyo_path = expand("~/.config/vim/src/SKK-JISYO.L")

  function! s:skkeleton_init() abort
    call skkeleton#config({
      \\ 'eggLikeNewline': v:false,
      \\ 'globalDictionaries': [s:jisyo_path],
      \\ })
  endfunction

  augroup skkeleton-initialize-pre
    autocmd!
    autocmd User skkeleton-initialize-pre call s:skkeleton_init()
  augroup END

  imap <C-j> <Plug>(skkeleton-toggle)
  cmap <C-j> <Plug>(skkeleton-toggle)
  tmap <C-j> <Plug>(skkeleton-toggle)
"""

[[plugins]]
repo = "sillybun/vim-repl"

# fzf & fzf.vim
[[plugins]]
repo = "junegunn/fzf"

[[plugins]]
repo = "junegunn/fzf.vim"
